---
- name: diable remote login of root
  hosts: hosts
  tasks: 
    - name: disable root remote login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        state: present
        line: "PermitRootLogin no"
       notify: reload sshd 
  handlers:
    - name: restart sshd
      service:
        name:sshd
        state: reloaded
